name: Selenium with TestNG - CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        continue-on-error: true
        env:
          PRESTASHOP_DBURL: ${{ secrets.PRESTASHOP_DBURL }}
          PRESTASHOP_DBUSER: ${{ secrets.PRESTASHOP_DBUSER }}
          PRESTASHOP_DBPASSWORD: ${{ secrets.PRESTASHOP_DBPASSWORD }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: ${{ github.workspace }}/target/surefire-reports/TEST-TestSuite.xml
          reporter: java-junit
          java-version: 11